/* Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

2^2=4, 2^3=8, 24=16, 25=32
3^2=9, 3^3=27, 34=81, 35=243
4^2=16, 4^3=64, 44=256, 45=1024
5^2=25, 53=125, 54=625, 55=3125
If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
 */

#include <stdio.h>
#include <math.h>
#include <gmp.h>
#include <stdlib.h>
#include <string.h>

#define MAX 100
// need to try for 100
#define MAX_SQUARED (MAX-1)*(MAX-1)

/*
int check_and_add(int new_int) {
   int i=-1;
   for(i=0;i<MAX*MAX;i++) {
      if(seq[i]==0) break; // reached end of sequence
      else if (seq[i] == new_int) return 1;
   }
   seq[i] = new_int;
   count += 1;
   return 1;
}
*/

int main(){

   printf("Euler 29\n\n");
   printf("max is %d\n",MAX);
   printf("max*max is %d\n\n-----\n",MAX_SQUARED);
   
   mpz_t a_big;
   mpz_t b_big;
   int flag;
   char all_products[MAX_SQUARED][201];
   int count = 0;

   mpz_init(a_big);
   mpz_init(b_big);

   int a=2,b=2;
   for (unsigned long int a=2;a<=MAX;a++) {
      for(unsigned long int b=2;b<=MAX;b++) {
         mpz_set_ui(a_big,a);
         mpz_set_ui(b_big,b);

         char b_big_string[201];

         mpz_pow_ui(b_big, b_big, a); // put b_big to the power of a back into b_big
         mpz_get_str(b_big_string,10,b_big);

         short int have_seen=0;
         for(int i=0;i<count;i++) {
            //~ printf("%s vs. %s; \n", b_big_string, all_products[i]);
            if(strcmp(all_products[i], b_big_string)==0) have_seen=1;
         }
         if(!have_seen) {
            strcpy(all_products[count], b_big_string);
            printf ("%s\n", b_big_string);
            count++;
         }
      }
   }

   mpz_clear(a_big);
   mpz_clear(b_big);
   printf("\nCount is %d and max was %d", count, MAX_SQUARED);
   printf("\n\nEnd.\n");
}
